### PR TITLE
Achievement Command Rework

### PR DESCRIPTION
**Pull request by TechnikTil**
This PR makes it so instead of pulling a generation from [minecraftskinstealer.com](https://minecraftskinstealer.com), it generates an achievement itself using `Canvas`

### CODE REVIEW

**Review by TechnikTil — COMMENTED** [review]
alright lets go

**Review by TechnikTil — COMMENTED** [review]
aw come on dude i never pushed i hate this game

**Comment by CrusherNotDrip** [comment]
im gonan remove the tasks.json just beczus i wanna impliment it myself

**Comment by TechnikTil** [comment]
Oh i didn't mean to push that mb

**Pull request merged**
